### ISSUE TITLE
pom.xml

### ISSUE THREAD

**Issue by emurigar** [Byclosure/bundler-maven-plugin#3]
Hi,
I have an error when I execute the command "mvn bundle:install", perhaps my pom.xml file is not well configured. 
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.mycompany.app</groupId>
  <artifactId>my-cucumber</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>my-app</name>
  <url>http://maven.apache.org</url>
  <dependencies>

    </dependencies>

    <build>
        <plugins>
          <plugin>
            <groupId>com.byclosure.maven.plugins</groupId>
          	<artifactId>bundler-maven-plugin</artifactId>
          	<version>0.0.3</version>
          </plugin>
        </plugins>
    </build>
</project>
```

Console output is the next one:
`[ERROR] Failed to execute goal com.byclosure.maven.plugins:bundler-maven-plugin:0.0.3:install (default-cli) on project my-cucumber: Execution default-cli of goal com.byclosure.maven.plugins:bundler-maven-plugin:0.0.3:install failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.byclosure.maven.plugins:bundler-maven-plugin:0.0.3:install (default-cli) on project my-cucumber: Execution default-cli of goal com.byclosure.maven.plugins:bundler-maven-plugin:0.0.3:install failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.byclosure.maven.plugins:bundler-maven-plugin:0.0.3:install failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at com.byclosure.maven.plugins.middleman.AbstractJRubyMojo.installBundler(AbstractJRubyMojo.java:126)
	at com.byclosure.maven.plugins.middleman.AbstractJRubyMojo.ensureBundlerInstalled(AbstractJRubyMojo.java:111)
	at com.byclosure.maven.plugins.middleman.AbstractJRubyMojo.execute(AbstractJRubyMojo.java:74)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more`

**Comment by oheavy** [comment]
Hi, this is related to the open [issue](https://github.com/Byclosure/bundler-maven-plugin/issues/2).
To solve this you need to add the following:
`<configuration>`
`    <working_dir>[Path to the folder with the Gemfile]</working_dir>`
`</configuration>`
